/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 src/Models/futuristic_rifle.glb 
Author: Charlie Baldwin (https://sketchfab.com/charlieatron)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/futuristic-rifle-c8d14a2ac6a14bdf9c56cd21c55f9c3d
Title: Futuristic Rifle
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/futuristic_rifle.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder42_bullet_0.geometry} material={materials.bullet} />
      <mesh geometry={nodes.pCylinder42_extraBits_0.geometry} material={materials.extraBits} />
      <mesh geometry={nodes.pCylinder42_barrel_0.geometry} material={materials.barrel} />
      <mesh geometry={nodes.pCylinder42_body_0.geometry} material={materials.body} />
      <mesh geometry={nodes.pCylinder42_magazine_0.geometry} material={materials.magazine} />
      <mesh geometry={nodes.pCylinder42_transparents_0.geometry} material={materials.transparents} />
    </group>
  )
}

useGLTF.preload('/futuristic_rifle.glb')
